// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcwhfqmnkmbupozcrtlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjd2hmcW1ua21idXBvemNydGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDQyMTksImV4cCI6MjA3MTI4MDIxOX0.859Hi6YaBZTthpZbU4na5-_OzZ3zTp19Cg8mNy2c2H0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});